### ISSUE TITLE
Valid Credentials in the Repo

### ISSUE THREAD

**Issue by Akamaozu** [IkoroVictor/BetAggregator-API#1]
Was checking out your code and saw your mongodb credentials in codebase.

https://github.com/IkoroVictor/BetAggregator-API/blob/master/index.js#L13

I crosschecked and they are live. You should remove them. Also probably wise to change every account where you use that password or something similar to it.

**Comment by IkoroVictor** [comment]
Thanks ..been removed.

**Comment by Akamaozu** [comment]
@IkoroVictor The data isn't in the current view of the repo, but anyone can go back to old commits and see it. There are automated tools that do this too. 

To be completely safe, I'd recommend checking this out: https://help.github.com/articles/remove-sensitive-data/

**Comment by IkoroVictor** [comment]
the password has been reset...and by the way...it was a test db...never planned on using db as a service

**Comment by Akamaozu** [comment]
Fair .... but now there's a record of your password bias.

It took every ounce if strength not to Google your email address and try that password on any accounts I could find related to it.

The owners of the crawlers though ... they're not that nice ;)

**Comment by IkoroVictor** [comment]
will keep that in mind
